Make trilead-putty extension as optional, transitive deps via trilead-api which was really used
jenkinsci/ssh-credentials-plugin pull request #200
Opened 2024-03-21 06:13 UTC by olamy

Signed-off-by: Olivier Lamy <olamy@apache.org>

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-03-21 11:23 UTC, jtnord commented
I have no idea how often putty style keys are used (mostly generated from windows users I guess), but if we need to the spec [is public](https://tartarus.org/~simon/putty-snapshots/htmldoc/AppendixC.html).

2024-03-21 12:00 UTC, jglick reviewed
Following up #199 I guess.

2024-03-21 12:00 UTC, jglick commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/SSHUserPrivateKey.java
> +    interface PrivateKeyReader {
Do we want to mark this `NoExternalUse`? Or just put it in the `impl` package?

2024-03-21 20:23 UTC, olamy commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/BasicSSHUserPrivateKey.java
>  import org.kohsuke.putty.PuTTYKey;
lol. fixed

2024-03-21 21:15 UTC, olamy commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/SSHUserPrivateKey.java
> +    interface PrivateKeyReader {
no real strong opinion. as it's treated as an extension, some could provide their own implementation but I have real doubts of this :)
maybe `NoExternalUse`.

2024-03-22 00:55 UTC, olamy commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/SSHUserPrivateKey.java
> +    interface PrivateKeyReader {
added `@Restricted(NoExternalUse.class)`

2024-03-22 18:29 UTC, jglick approved these changes

2024-03-22 18:29 UTC, jglick commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/BasicSSHUserPrivateKey.java
> +                    }
More simply
```suggestion
                    for (PrivateKeyReader reader : ExtensionList.lookup(PrivateKeyReader.class)) {
                        if(reader.accept(privateKey)) {
                            privateKeys.add(reader.toOpenSSH(privateKey, passphrase));
                            continue;
                        }
                    }
```
right?

2024-03-22 18:29 UTC, jglick commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/SSHUserPrivateKey.java
> +         * @return {@code true} if this reader can use such format
Could also just delete this method and let `toOpenSSH` return null if unrecognized.

2024-03-25 01:23 UTC, olamy commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/SSHUserPrivateKey.java
> +         * @return {@code true} if this reader can use such format
yup done. as we will have only one implementation of this. that will reduce slight code size

2024-03-25 12:38 UTC, jglick requested changes

2024-03-25 12:38 UTC, jglick commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/BasicSSHUserPrivateKey.java
> +                            break;
I think you want to break out of the outer loop (meaning adding a label) rather than the inner loop. Otherwise for a PuTTY key you will add two entries to `privateKeys`.

(Is there no test coverage for this?)

2024-03-26 04:40 UTC, olamy commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/BasicSSHUserPrivateKey.java
> +                            break;
well I'm really  tempted to remove this putty key extension as this is not up to date and doesn't even work with current version of PuTTy.
using something such `puttygen -t rsa -b 2048 -o mykey.ppk
uttygen -t rsa -b 2048 -o mykey.ppk
`
you get a file starting with 
```
PuTTY-User-Key-File-3: ssh-rsa
```
This key will simply generate a NPE because of this line https://github.com/kohsuke/trilead-putty-extension/blob/e928d8b5cc80a35d521b05e8256bdd5100cba616/src/main/java/org/kohsuke/putty/PuTTYKey.java#L149

So I'm just tempted to remove this code which simply doesn't work anymore...

2024-03-26 21:32 UTC, olamy commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/BasicSSHUserPrivateKey.java
> +                            break;
So, in the last 3 years, no single key created with PuTTy could have been used.
I couldn't find any issue reported in Jira...
It looks like we can remove the support of the PuTTy key format.
I'm not sure why someone re-invented the wheel by inventing another format.

https://xkcd.com/927/

2024-03-26 22:26 UTC, jtnord reviewed
Seems reasonable to remove, but I'm sure someone will be using an old V2 key from a server configured long ago...
Not sure why putty keys were not using a different Key source to begin with though

2024-03-26 22:26 UTC, jtnord commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/SSHUserPrivateKey.java
> +import java.io.IOException;
No longer required?

2024-03-26 22:26 UTC, jtnord commented on src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/BasicSSHUserPrivateKey.java
> +import hudson.ExtensionList;
No longer required?

2024-03-27 06:54 UTC, olamy commented
> Seems reasonable to remove, but I'm sure someone will be using an old V2 key from a server configured long ago... 

Easy bet to win :)

2024-03-27 08:48 UTC, jtnord approved these changes
Seems reasonable to me, but will delay merging to let others have an opinion

2024-03-27 11:40 UTC, jglick approved these changes

2024-03-27 11:40 UTC, merged

2024-03-28 17:12 UTC, salsifis commented
> Seems reasonable to remove, but I'm sure someone will be using an old V2 key from a server configured long ago... Not sure why putty keys were not using a different Key source to begin with though

I can announce that you won your bet :)

Here is, for those who will encounter this problem, how to convert your older PuTTY credentials to more standard ones:

* Open PuTTYgen
* Load your key in the PuTTY format (.ppk) using the passphrase
* Click “Conversions” › Export OpenSSH key (force new file format)

The resulting file can be used as the private key in a new credentials entry, with the same passphrase.

2024-03-28 17:20 UTC, jglick commented
@salsifis I took the liberty of adding your instructions (unconfirmed) to https://github.com/jenkinsci/ssh-credentials-plugin/releases/tag/334.v7732563deee1 for better discoverability. @olamy / @jtnord should this be reverted and the originally proposed extension point reintroduced?

2024-03-28 17:29 UTC, jtnord commented
> . @olamy / @jtnord should this be reverted and the originally proposed extension point reintroduced?

I am in 2 minds here.  
on the one hand I do not like breaking things, 
on the other the ep (and the old code as implemented) seemed to violate the kiss principal, and the UI does not purport to support these keys (nor does it purport to support OpenSSH keys - so that may be a moot point, however it is producing only OpenSSH based keys for use).

2024-03-29 00:23 UTC, olamy commented
@salsifis congratulations! bravo :)
I agree it's usually not a good idea to break things.
But here the putty key support is kind of obscure (not even clearly documented and coming from some libraries called trilead) and really poor as we do not support keys generated by the last version of Putty.
And the migration of the key looks to be very easy and thanks @jglick adding it to the release notes.

2024-03-29 07:32 UTC, salsifis commented
@olamy @jtnord

In my opinion the main problem here is that this end of support was not announced (no warnings or whatever in the Jenkins interface). We had to look at the Jenkins logs and do some research to understand why an update caused the jobs to abort.

It would be better to have warnings if deprecations are on the table.

2024-04-02 12:00 UTC, jtnord commented
@olamy can you add the `compatable-since` to the hpi plugin configuration (denoting the first version that removed the support) - that way it will at least get the warning to prompt users to go to the release notes.

2024-04-03 01:48 UTC, olamy commented
That sounds like a good idea. https://github.com/jenkinsci/ssh-credentials-plugin/pull/202